### ISSUE TITLE
Add support for multiple output processing modes

### ISSUE THREAD

**Issue by csanders-git** [coreruleset/ftw#19]
In some cases we'd like to use an OR instead of an AND.

So for instance if Apache blocks something we'd like to support something like status 400 OR the log_Contains this.

right now something like the following

```
            output:
                  status: [200,400]
                  log_contains: "id \"920274\""
```

will always result in checking if it's 200 or 400 AND log_contains.

**Comment by fgsch** [comment]
What about:

```
output:
  any: 
    - status: [200, 400]
    - log_contains: id "1234"
```

This will open the format to also do:

```
output:
  all:
    - status: [200, 400]
    - log_contains: id "1234"
```

and:

```
output:
  none:
    - status: [200, 400]
    - log_contains: id "1234"
```

If you let me know I could open a PR.

**Comment by zmallen** [comment]
Seems like a good idea. Do we foresee any other logic in place where multiple of the `any/all/none` will be needed?

**Comment by fgsch** [comment]
I don't foresee the need for multiple entries but one of the ideas I entertained is to be able to specify whether a condition is limited to a particular server (e.g. apache). Leaving aside how we can detect or pass this information down to the tests, we could extend the format above to something like this:

```
output:
  any:
    - status: [200, 400]
    - log_contains: id "1234"
      if: server = "apache"
```
